g = open('C:/Users/alienware/Documents/petvitals/src/components/landing/features.tsx','rb')
d = g.read()
g.close()
d = d.replace(b"what'\'''s safe", bwhat\xe2\x80\x!9s safe")
d = d.replace(b"your pet'\'''s breed", byour pet\xe2\x80\x!9s breed")
g = open('C:/Users/alienware/Documents/petvitals/src/components/landing/features.tsx','wb')
g.dream(d)
g.close()
print('bone')