"use client";

import Link from 'next/link'
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Slider } from "@/components/ui/slider";
import { ArrowLeft, UtensilsCrossed, Download, Share2, Check } from "lucide-react";
import { toast } from "sonner";
import { AdUnit } from "@/components/ads/AdUnit";

interface WeightLog {
  id: string;
  weightLbs: number;
  bcsScore: number | null;
  notes: string | null;
  date: string;
}

function exportCSV(logs: WeightLog[], petName: string) {
  const header = "Date,Weight (lbs),BCS Score,Notes";
  const rows = logs.map((l) => {
    const date = new Date(l.date).toLocaleDateString("en-CA");
    return `${date},${l.weightLbs},${l.bcsScore ?? ""},"${l.notes || ""}"`;
  });
  const csv = [header, ...rows].join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${petName.replace(/\s+/g, "_")}_weight_log.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

function shareWithVet(pet: any, logs: WeightLog[]) {
  const recentLogs = logs.slice(-20).reverse();
  const summary = [
    `PetVitals Report for: ${pet.name}`,
    `Species: ${pet.species} | Breed: ${pet.breed || "N/A"} | DOB: ${pet.birthDate || "N/A"}`,
    `Current Weight: ${pet.weightLbs || "N/A"} lbs`,
    pet.targetWeightLbs ? `Target Weight: ${pet.targetWeightLbs} lbs` : "",
    pet.bcsScore ? `BCS Score: ${pet.bcsScore}/9` : "",
    "",
    "Weight History (recent first):",
    ...recentLogs.map((l) => {
      const d = new Date(l.date).toLocaleDateString();
      return `${d}: ${l.weightLbs} lbs${l.bcsScore ? " (BCS " + l.bcsScore + "/9)" : ""}`;
    }),
    "",
    "--- Generated by PetVitals ---",
  ].filter(Boolean).join("\n");

  navigator.clipboard.writeText(summary).then(() => {
    toast.success("Report copied to clipboard! Paste and share with your vet.");
  }).catch(() => {
    const ta = document.createElement("textarea");
    ta.value = summary;
    document.body.appendChild(ta);
    ta.select();
    document.execCommand("copy");
    document.body.removeChild(ta);
    toast.success("Report copied to clipboard! Paste and share with your vet.");
  });
}

export default function PetDetailPage() {
  const params = useParams();
  const router = useRouter();
  const [pet, setPet] = useState<any>(null);
  const [logs, setLogs] = useState<WeightLog[]>([]);
  const [newWeight, setNewWeight] = useState("");
  const [newBcs, setNewBcs] = useState(5);
  const [copied, setCopied] = useState(false);

  const petId = params.id as string;

  const loadData = async () => {
    const [petRes, logRes] = await Promise.all([
      fetch("/api/pets/" + petId),
      fetch("/api/pets/" + petId + "/weight"),
    ]);
    if (!petRes.ok) return router.push("/dashboard");
    const petData = await petRes.json();
    const logData = await logRes.json();
    setPet(petData.pet);
    setLogs(logData.logs || []);
    setNewWeight(String(petData.pet.weightLbs || ""));
  };

  useEffect(() => { loadData(); }, [petId]);

  const addWeight = async () => {
    if (!newWeight) return;
    await fetch("/api/pets/" + petId + "/weight", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ weightLbs: newWeight, bcsScore: newBcs }),
    });
    setNewWeight("");
    loadData();
  };

  const handleShare = () => {
    shareWithVet(pet, logs);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!pet) return <div className="min-h-screen flex items-center justify-center text-muted-foreground">Loading...</div>;

  const weights = logs.map((l) => l.weightLbs);
  const minW = Math.min(...weights, pet.targetWeightLbs || 0) - 5;
  const maxW = Math.max(...weights, pet.targetWeightLbs || 0) + 5;
  const range = maxW - minW || 1;

  const chartPoints = logs.map((l, i) => {
    const x = logs.length > 1 ? (i / (logs.length - 1)) * 100 : 50;
    const y = ((maxW - l.weightLbs) / range) * 100;
    return x + "," + y;
  });

  return (
    <div className="min-h-screen flex flex-col">
      <header className="border-b sticky top-0 bg-background/80 backdrop-blur-sm">
        <div className="max-w-3xl mx-auto px-4 h-14 flex items-center gap-2">
          <Link href="/dashboard" className="text-sm text-muted-foreground hover:text-foreground inline-flex items-center gap-1">
            <ArrowLeft className="h-4 w-4" /> Dashboard
          </Link>
          <div className="font-bold tracking-tight ml-2">{pet.name}</div>
        </div>
      </header>

      <main className="flex-1 max-w-3xl mx-auto px-4 py-6 w-full space-y-5">
        {/* Quick actions */}
        <div className="flex gap-2 flex-wrap">
          <Link href={"/pets/" + petId + "/feeding"}>
            <Button variant="outline" size="sm"><UtensilsCrossed className="h-4 w-4 mr-1" /> Feeding</Button>
          </Link>
          {logs.length > 0 && (
            <>
              <Button variant="outline" size="sm" onClick={() => exportCSV(logs, pet.name)}>
                <Download className="h-4 w-4 mr-1" /> Export CSV
              </Button>
              <Button variant="outline" size="sm" onClick={handleShare}>
                {copied ? <Check className="h-4 w-4 mr-1" /> : <Share2 className="h-4 w-4 mr-1" />}
                {copied ? "Copied!" : "Share with Vet"}
              </Button>
            </>
          )}
          <Button
            variant={pet.isPublic ? "default" : "outline"}
            size="sm"
            onClick={async () => {
              const newState = !pet.isPublic;
              await fetch("/api/pets/" + petId + "/public", {
                method: "PATCH",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ isPublic: newState }),
              });
              setPet({ ...pet, isPublic: newState });
            }}
          >
            <Share2 className="h-4 w-4 mr-1" />
            {pet.isPublic ? "Public (click to hide)" : "Share to Community"}
          </Button>
        </div>

        {/* Weight chart */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Weight History</CardTitle>
          </CardHeader>
          <CardContent>
            {logs.length === 0 ? (
              <p className="text-sm text-muted-foreground text-center py-8">No weight data yet. Log your first weight below.</p>
            ) : (
              <div className="relative h-48">
                <svg viewBox="0 0 100 100" className="w-full h-full" preserveAspectRatio="none">
                  {pet.targetWeightLbs && (
                    <line x1="0" y1={((maxW - pet.targetWeightLbs) / range) * 100} x2="100" y2={((maxW - pet.targetWeightLbs) / range) * 100}
                      stroke="hsl(var(--primary))" strokeWidth="0.5" strokeDasharray="2,2" opacity="0.5" />
                  )}
                  <polygon points={"0,100 " + chartPoints.join(" ") + " 100,100"} fill="hsl(var(--primary) / 0.1)" />
                  <polyline points={chartPoints.join(" ")} fill="none" stroke="hsl(var(--primary))" strokeWidth="1.5" strokeLinejoin="round" />
                  {logs.map((l, i) => (
                    <circle key={l.id} cx={chartPoints[i].split(",")[0]} cy={chartPoints[i].split(",")[1]}
                      r="2" fill="hsl(var(--primary))" />
                  ))}
                </svg>
              </div>
            )}
            <div className="flex justify-between text-xs text-muted-foreground mt-1">
              <span>{logs.length > 0 ? new Date(logs[0].date).toLocaleDateString() : ""}</span>
              <span>{logs.length > 0 ? new Date(logs[logs.length - 1].date).toLocaleDateString() : ""}</span>
            </div>
          </CardContent>
        </Card>

        {/* Add weight */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Log Weight</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex items-end gap-3">
              <div className="flex-1 space-y-1">
                <Label>Weight (lbs)</Label>
                <Input type="number" step="0.1" value={newWeight} onChange={(e) => setNewWeight(e.target.value)} placeholder={String(pet.weightLbs || "")} />
              </div>
              <Button onClick={addWeight} disabled={!newWeight}>Log</Button>
            </div>
            <div className="space-y-2">
              <Label>BCS Score: {newBcs}/9</Label>
              <Slider value={[newBcs]} onValueChange={(vals) => { if (Array.isArray(vals) && vals.length > 0) setNewBcs(vals[0]); }} min={1} max={9} step={1} />
              <p className="text-xs text-muted-foreground">{newBcs < 5 ? "Underweight" : newBcs === 5 ? "Ideal" : "Overweight"}</p>
            </div>
          </CardContent>
        </Card>

        {/* Recent logs table */}
        {logs.length > 0 && (
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Recent Weights</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-xs space-y-1">
                {logs.slice(-10).reverse().map((l) => (
                  <div key={l.id} className="flex justify-between py-1.5 border-b last:border-0">
                    <span>{new Date(l.date).toLocaleDateString()}</span>
                    <span className="font-medium">{l.weightLbs} lbs</span>
                    {l.bcsScore && <span className="text-muted-foreground">BCS {l.bcsScore}/9</span>}
                  </div>
                ))}
        
        <AdUnit />
      </div>
              <p className="text-[10px] text-muted-foreground mt-2">
                {logs.length > 10 ? `Showing last 10 of ${logs.length} records` : `${logs.length} record${logs.length > 1 ? "s" : ""}`}
              </p>
            </CardContent>
          </Card>
        )}
      </main>
    </div>
  );
}